// Autogenerated from Pigeon (v3.1.5), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class LocationStatus;
@class LocationCoordinate;

@interface LocationStatus : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithStatus:(NSString *)status;
@property(nonatomic, copy) NSString * status;
@end

@interface LocationCoordinate : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithLatitude:(NSNumber *)latitude
    longitude:(NSNumber *)longitude;
@property(nonatomic, strong) NSNumber * latitude;
@property(nonatomic, strong) NSNumber * longitude;
@end

/// The codec used by LocationAPI.
NSObject<FlutterMessageCodec> *LocationAPIGetCodec(void);

@protocol LocationAPI
/// @return `nil` only when `error != nil`.
- (nullable LocationStatus *)getLocationStatusWithError:(FlutterError *_Nullable *_Nonnull)error;
- (nullable LocationCoordinate *)getLocationCoordWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)requestLocationPermissionWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)listenLocationCoordinateWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)stopListenLocationCoordinateWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void LocationAPISetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<LocationAPI> *_Nullable api);

NS_ASSUME_NONNULL_END
